# Generated by Django 5.1.7 on 2025-03-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(help_text='Remix icon class name', max_length=50)),
                ('color_class', models.CharField(help_text='Tailwind color class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Social Stats',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='tutorials/')),
                ('read_time', models.PositiveIntegerField(help_text='Estimated read time in minutes')),
                ('published_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='tutorials.category')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.platform')),
            ],
        ),
    ]
